language: node_js
node_js:
- node
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
before_deploy:
- npm run build
deploy:
  provider: npm
  email: anthony.kerz@gmail.com
  api_key:
    secure: gSw34eAjBAJNwwTxodlZw2BnbvFe9ri5KN+JEIJnREcOcvWZk2ZAFo4bXep3RHFdYUZMCzMy7xfAib6BW+kY3hGWFnBb6MacIYtMOp7nuOC/CD2zRkp09j92a+Z2GaUMGZ+jixNkYGhr566lVMIGznSfvZtjBu9Rs9CRyFkbn4e6Z7+T0D4sle07oZuPnpNYhjKmuDhfhD9N+FTmvhcGafAlotOCqei2mbSAMC7D7pKFotfQSCaQjt1zQteSw8TQXcz1GswyndLUbF/TCtT+LB39M0Zy90poxgU9QIZnw/AD+mFlPrw+mmPBA+wfwpak2FMnBafByZfv3Y8CTUC2t82Th63YB0iJCjdJSldVJbWAZLvMwOef8Bol353CX4fL6921+rcp7eQEblhw+MaMlswxVWVebHQDZxZQvCUj4mkg/tYKBxZgLp1qbC+cV4kD/Oz/wh/vdYI90N6nnNuCvvd7V/1odWjVGCA47ysiTCoGKT1kZ0Mv3/BXpTqpp+b6w8jyx4ieOgxnvjm4C2uUvjfRkF8vbf2cmZhYNmalgx/r54FOx1HaPkopuHFZEFHoG7uQ5qD0ntcfh+Y/Vv667CZfMwgh+rGKCXAoC8yBa7F9I8Wy/ofohL42uXgp9lsiHdAdIEGNZ4li4twXxGrGJJ8IgxxqqfvwPgyRWLVsJrc=
  skip_cleanup: true
  on:
    branch: master
    condition: "-z $TRAVIS_TAG"
